# Site settings
title: Paweł Nguyen
header-img: img/home-bg.jpg
email: pawel.nguyen@gmail.com
description: "Full-stack Ruby on Rails developer, Scrum Master and startup enthusiast"
baseurl: ""
url: "http://pawelnguyen.github.io"
twitter_username: pawel_nguyen
github_username:  pawelnguyen
linkedin_username: pawelnguyen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
